### ISSUE TITLE
Crash on iOS simulator, 12.1

### ISSUE THREAD

**Issue by adriansergheev** [danielt1263/RxMultipeerGroupChat#1]
2019-03-25 08:48:02.895237+0100 RxMultipeerGroupChat[84713:2253899] Presenting view controllers on detached view controllers is discouraged <RxMultipeerGroupChat.MainViewController: 0x7fc5a7914350>.
2019-03-25 08:48:03.509400+0100 RxMultipeerGroupChat[84713:2253899] Unbalanced calls to begin/end appearance transitions for <UINavigationController: 0x7fc5a702b600>.
2019-03-25 08:48:04.369103+0100 RxMultipeerGroupChat[84713:2253899] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /Users/sergheev/Library/Developer/CoreSimulator/Devices/03F5ADE2-F2E1-4EA4-949D-623B91191588/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2019-03-25 08:48:04.370195+0100 RxMultipeerGroupChat[84713:2253899] [MC] Reading from private effective user settings.
2019-03-25 08:48:12.633482+0100 RxMultipeerGroupChat[84713:2253899] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid serviceType passed to MCNearbyServiceAdvertiser'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010ce741bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x000000010c412735 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ce74015 +[NSException raise:format:] + 197
	3   MultipeerConnectivity               0x000000010daa1890 -[MCNearbyServiceAdvertiser initWithPeer:discoveryInfo:serviceType:] + 406
	4   RxMultipeerGroupChat                0x000000010b40a66d $SSo25MCNearbyServiceAdvertiserC4peer13discoveryInfo11serviceTypeABSo8MCPeerIDC_SDyS2SGSgSStcfcTO + 173
	5   RxMultipeerGroupChat                0x000000010b4099b3 $SSo25MCNearbyServiceAdvertiserC4peer13discoveryInfo11serviceTypeABSo8MCPeerIDC_SDyS2SGSgSStcfC + 83
	6   RxMultipeerGroupChat                0x000000010b408fd8 $S20RxMultipeerGroupChat22SettingsViewControllerC32isDisplayNameAndSerivceTypeValid33_7D311714FB3F932A56EA1A4560C81E32LLSbvg + 12936
	7   RxMultipeerGroupChat                0x000000010b4056e5 $S20RxMultipeerGroupChat22SettingsViewControllerC10doneTappedyyF + 37
	8   RxMultipeerGroupChat                0x000000010b4053f4 $S20RxMultipeerGroupChat22SettingsViewControllerC11viewDidLoadyyFyycfU_ + 180
	9   RxMultipeerGroupChat                0x000000010b40541c $S20RxMultipeerGroupChat22SettingsViewControllerC11viewDidLoadyyFyycfU_TA + 12
	10  RxMultipeerGroupChat                0x000000010b3e7edc $SIeg_ytIegn_TR + 12
	11  RxMultipeerGroupChat                0x000000010b405471 $SIeg_ytIegn_TRTA + 17
	12  RxSwift                             0x000000010baa9bdc $S7RxSwift14ObservableTypePAAE9subscribe6onNext0F5Error0F9Completed0F8DisposedAA10Disposable_py1EQzcSg_ys0H0_pcSgyycSgAOtFyAA5EventOyAKGcfU_ + 716
	13  RxSwift                             0x000000010baa9fe7 $S7RxSwift14ObservableTypePAAE9subscribe6onNext0F5Error0F9Completed0F8DisposedAA10Disposable_py1EQzcSg_ys0H0_pcSgyycSgAOtFyAA5EventOyAKGcfU_TA + 103
	14  RxSwift                             0x000000010ba004df $S7RxSwift17AnonymousObserverC6onCoreyyAA5EventOyxGF + 95
	15  RxSwift                             0x000000010bab0316 $S7RxSwift12ObserverBaseC2onyyAA5EventOyxGF + 486
	16  RxSwift                             0x000000010bab0755 $S7RxSwift12ObserverBaseCyxGAA0C4TypeA2aEP2onyyAA5EventOy1EQzGFTW + 21
	17  RxSwift                             0x000000010baf6cea $S7RxSwift4SinkC9forwardOnyyAA5EventOy1EQzGF + 410
	18  RxSwift                             0x000000010bafe9f6 $S7RxSwift15SubscribeOnSink33_B44C3DD7F62EF81799E6347E59A266A2LLC2onyyAA5EventOy1EQzGF + 246
	19  RxSwift                             0x000000010baff380 $S7RxSwift15SubscribeOnSink33_B44C3DD7F62EF81799E6347E59A266A2LLCyxq_GAA12ObserverTypeA2aFP2onyyAA5EventOy1EQzGFTW + 16
	20  RxSwift                             0x000000010ba016b6 $STA + 102
	21  RxSwift                             0x000000010ba09097 $S7RxSwift5EventOyxGIegn_ADytIegnr_1EQyd__RszAA12ObserverTypeRd__r__lTR + 23
	22  RxSwift                             0x000000010baeec66 $S7RxSwift5EventOyxGIegn_ADytIegnr_1EQyd__RszAA12ObserverTypeRd__r__lTRTA + 54
	23  RxSwift                             0x000000010ba095e0 $S7RxSwift5EventOyxGytIegnr_ADIegn_lTR + 16
	24  RxSwift                             0x000000010ba0aeb0 $S7RxSwift5EventOyxGytIegnr_ADIegn_lTRTA.8 + 32
	25  RxSwift                             0x000000010ba0a51e $S7RxSwift8dispatchyyAA3BagVyyAA5EventOyxGcG_AGtlF + 414
	26  RxSwift                             0x000000010baecb0a $S7RxSwift29ShareWhileConnectedConnection33_E9FE621655D67A613BF2FC2D9B3041FCLLC2onyyAA5EventOyxGF + 138
	27  RxSwift                             0x000000010baee0a0 $S7RxSwift29ShareWhileConnectedConnection33_E9FE621655D67A613BF2FC2D9B3041FCLLCyxGAA12ObserverTypeA2aFP2onyyAA5EventOy1EQzGFTW + 16
	28  RxSwift                             0x000000010baf6cea $S7RxSwift4SinkC9forwardOnyyAA5EventOy1EQzGF + 410
	29  RxSwift                             0x000000010bb0fa87 $S7RxSwift13TakeUntilSink33_991BF34058B438BC3F322FA2B2904AFELLC16_synchronized_onyyAA5EventOy1EQy_GF + 375
	30  RxSwift                             0x000000010bb10239 $S7RxSwift13TakeUntilSink33_991BF34058B438BC3F322FA2B2904AFELLCyxq_GAA18SynchronizedOnTypeA2aFP16_synchronized_onyyAA5EventOy1EQzGFTW + 9
	31  RxSwift                             0x000000010bb06737 $S7RxSwift18SynchronizedOnTypePAAE012synchronizedD0yyAA5EventOy1EQzGF + 151
	32  RxSwift                             0x000000010bb0f8fe $S7RxSwift13TakeUntilSink33_991BF34058B438BC3F322FA2B2904AFELLC2onyyAA5EventOy1EQy_GF + 190
	33  RxSwift                             0x000000010bb10220 $S7RxSwift13TakeUntilSink33_991BF34058B438BC3F322FA2B2904AFELLCyxq_GAA12ObserverTypeA2aFP2onyyAA5EventOy1EQzGFTW + 16
	34  RxSwift                             0x000000010baf6cea $S7RxSwift4SinkC9forwardOnyyAA5EventOy1EQzGF + 410
	35  RxSwift                             0x000000010ba5f353 $S7RxSwift23AnonymousObservableSink33_95EBF5692819D58425EC2DD0512D115ALLC2onyyAA5EventOy1EQzGF + 531
	36  RxSwift                             0x000000010ba5f770 $S7RxSwift23AnonymousObservableSink33_95EBF5692819D58425EC2DD0512D115ALLCyxGAA12ObserverTypeA2aFP2onyyAA5EventOy1EQzGFTW + 16
	37  RxSwift                             0x000000010ba016b6 $STA + 102
	38  RxSwift                             0x000000010ba00b98 $S7RxSwift11AnyObserverV2onyyAA5EventOyxGF + 72
	39  RxCocoa                             0x000000010b824be9 $S7RxSwift8ReactiveV0A5CocoaSo15UIBarButtonItemCRbzlE3tapAD12ControlEventVyytGvgAA10ObservableCyytGyXEfU_AA10Disposable_pAA11AnyObserverVyytGcfU_yycfU_ + 73
	40  RxCocoa                             0x000000010b825bd1 $S7RxSwift8ReactiveV0A5CocoaSo15UIBarButtonItemCRbzlE3tapAD12ControlEventVyytGvgAA10ObservableCyytGyXEfU_AA10Disposable_pAA11AnyObserverVyytGcfU_yycfU_TA + 17
	41  RxCocoa                             0x000000010b825710 $S7RxCocoa19BarButtonItemTargetC6actionyyyXlF + 272
	42  RxCocoa                             0x000000010b82576c $S7RxCocoa19BarButtonItemTargetC6actionyyyXlFTo + 60
	43  UIKitCore                           0x0000000116804ecb -[UIApplication sendAction:to:from:forEvent:] + 83
	44  UIKitCore                           0x0000000115f4595b __45-[_UIButtonBarTargetAction _invoke:forEvent:]_block_invoke + 154
	45  UIKitCore                           0x0000000115f45894 -[_UIButtonBarTargetAction _invoke:forEvent:] + 152
	46  UIKitCore                           0x0000000116804ecb -[UIApplication sendAction:to:from:forEvent:] + 83
	47  UIKitCore                           0x00000001162400bd -[UIControl sendAction:to:forEvent:] + 67
	48  UIKitCore                           0x00000001162403da -[UIControl _sendActionsForEvents:withEvent:] + 450
	49  UIKitCore                           0x000000011623f31e -[UIControl touchesEnded:withEvent:] + 583
	50  UIKitCore                           0x00000001168400a4 -[UIWindow _sendTouchesForEvent:] + 2729
	51  UIKitCore                           0x00000001168417a0 -[UIWindow sendEvent:] + 4080
	52  UIKitCore                           0x000000011681f394 -[UIApplication sendEvent:] + 352
	53  UIKitCore                           0x00000001168f45a9 __dispatchPreprocessedEventFromEventQueue + 3054
	54  UIKitCore                           0x00000001168f71cb __handleEventQueueInternal + 5948
	55  CoreFoundation                      0x000000010cdd9721 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	56  CoreFoundation                      0x000000010cdd8f93 __CFRunLoopDoSources0 + 243
	57  CoreFoundation                      0x000000010cdd363f __CFRunLoopRun + 1263
	58  CoreFoundation                      0x000000010cdd2e11 CFRunLoopRunSpecific + 625
	59  GraphicsServices                    0x0000000113e301dd GSEventRunModal + 62
	60  UIKitCore                           0x000000011680381d UIApplicationMain + 140
	61  RxMultipeerGroupChat                0x000000010b3f5cd7 main + 71
	62  libdyld.dylib                       0x0000000110004575 start + 1
	63  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by danielt1263** [comment]
What commit were you on when this crash happened? Had you already run the app successfully once, or was this on first run?

**Comment by adriansergheev** [comment]
Just checked now, it happens on the last commit as well.
First run, on clicking on "Done".

`2019-04-22 09:01:39.874885+0200 RxMultipeerGroupChat[81164:2534901] Presenting view controllers on detached view controllers is discouraged <RxMultipeerGroupChat.MainViewController: 0x7ffad88207f0>.
2019-04-22 09:01:40.491845+0200 RxMultipeerGroupChat[81164:2534901] Unbalanced calls to begin/end appearance transitions for <UINavigationController: 0x7ffad681ae00>.
2019-04-22 09:01:44.381219+0200 RxMultipeerGroupChat[81164:2534901] [MC] System group container for systemgroup.com.apple.configurationprofiles path is /Users/sergheev/Library/Developer/CoreSimulator/Devices/17F86C40-99E9-4E30-8F83-B9FF8FA3D176/data/Containers/Shared/SystemGroup/systemgroup.com.apple.configurationprofiles
2019-04-22 09:01:44.382242+0200 RxMultipeerGroupChat[81164:2534901] [MC] Reading from private effective user settings.
create new session
2019-04-22 09:01:47.327865+0200 RxMultipeerGroupChat[81164:2534901] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Invalid displayName passed to MCPeerID'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001088f56fb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000107ea1ac5 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001088f5555 +[NSException raise:format:] + 197
	3   MultipeerConnectivity               0x0000000107771a2f -[MCPeerID initWithDisplayName:] + 212
	4   RxMultipeerGroupChat                0x0000000106cc503c $sSo8MCPeerIDC11displayNameABSS_tcfcTO + 44
	5   RxMultipeerGroupChat                0x0000000106cbc0e2 $sSo8MCPeerIDC11displayNameABSS_tcfC + 50
	6   RxMultipeerGroupChat                0x0000000106cbab70 $s20RxMultipeerGroupChat16SessionContainerC11displayName11serviceTypeACSS_SStcfc + 384
	7   RxMultipeerGroupChat                0x0000000106cba98b $s20RxMultipeerGroupChat16SessionContainerC11displayName11serviceTypeACSS_SStcfC + 75
	8   RxMultipeerGroupChat                0x0000000106cd4e9d $s20RxMultipeerGroupChat18MainViewControllerC11viewDidLoadyyFAA16SessionContainerCSS_SStcfU8_ + 125
	9   RxMultipeerGroupChat                0x0000000106cd4efb $sS2S20RxMultipeerGroupChat16SessionContainerCs5Error_pIegggozo_SS_SStACsAD_pIegnrzo_TR + 75
	10  RxMultipeerGroupChat                0x0000000106cd4fbb $sS2S20RxMultipeerGroupChat16SessionContainerCs5Error_pIegggozo_SS_SStACsAD_pIegnrzo_TRTA + 27
	11  RxSwift                             0x00000001073aee9b $s7RxSwift7MapSink33_5428EFA9A9B0C0340021B871D2E5AC01LLC2onyyAA5EventOyxGF + 731
	12  RxSwift                             0x00000001073afcf0 $s7RxSwift7MapSink33_5428EFA9A9B0C0340021B871D2E5AC01LLCyxq_GAA12ObserverTypeA2aFP2onyyAA5EventOy1EQzGFTW + 16
	13  RxSwift                             0x000000010742bdb3 $s7RxSwift4SinkC9forwardOnyyAA5EventOy1EQzGF + 275
	14  RxSwift                             0x000000010746ef50 $s7RxSwift18WithLatestFromSink33_CF69D82A190E869E15F230EB33D8E9CBLLC16_synchronized_onyyAA5EventOyxGF + 1264
	15  RxSwift                             0x000000010746ffb9 $s7RxSwift18WithLatestFromSink33_CF69D82A190E869E15F230EB33D8E9CBLLCyxq_q0_GAA18SynchronizedOnTypeA2aFP16_synchronized_onyyAA5EventOy1EQzGFTW + 9
	16  RxSwift                             0x000000010744278f $s7RxSwift18SynchronizedOnTypePAAE012synchronizedD0yyAA5EventOy1EQzGF + 175
	17  RxSwift                             0x000000010746ea56 $s7RxSwift18WithLatestFromSink33_CF69D82A190E869E15F230EB33D8E9CBLLC2onyyAA5EventOyxGF + 166
	18  RxSwift                             0x000000010746ff90 $s7RxSwift18WithLatestFromSink33_CF69D82A190E869E15F230EB33D8E9CBLLCyxq_q0_GAA12ObserverTypeA2aFP2onyyAA5EventOy1EQzGFTW + 16
	19  RxSwift                             0x000000010742bdb3 $s7RxSwift4SinkC9forwardOnyyAA5EventOy1EQzGF + 275
	20  RxSwift                             0x0000000107391d2b $s7RxSwift6DoSink33_51F9E615740E91B2E920965FFBB1EED3LLC2onyyAA5EventOy1EQzGF + 379
	21  RxSwift                             0x0000000107392a20 $s7RxSwift6DoSink33_51F9E615740E91B2E920965FFBB1EED3LLCyxGAA12ObserverTypeA2aFP2onyyAA5EventOy1EQzGFTW + 16
	22  RxSwift                             0x000000010742bdb3 $s7RxSwift4SinkC9forwardOnyyAA5EventOy1EQzGF + 275
	23  RxSwift                             0x00000001073bfe7e $s7RxSwift13MergeSinkIter33_DDEA0423368B3B462AE46699A4D080E1LLC2onyyAA5EventOy1EQy_GF + 606
	24  RxSwift                             0x00000001073c0180 $s7RxSwift13MergeSinkIter33_DDEA0423368B3B462AE46699A4D080E1LLCyxq_q0_GAA12ObserverTypeA2aFP2onyyAA5EventOy1EQzGFTW + 16
	25  RxSwift                             0x000000010742bdb3 $s7RxSwift4SinkC9forwardOnyyAA5EventOy1EQzGF + 275
	26  RxSwift                             0x00000001073aef2a $s7RxSwift7MapSink33_5428EFA9A9B0C0340021B871D2E5AC01LLC2onyyAA5EventOyxGF + 874
	27  RxSwift                             0x00000001073afcf0 $s7RxSwift7MapSink33_5428EFA9A9B0C0340021B871D2E5AC01LLCyxq_GAA12ObserverTypeA2aFP2onyyAA5EventOy1EQzGFTW + 16
	28  RxSwift                             0x0000000107303ac3 $sTA + 83
	29  RxSwift                             0x000000010730bfcc $s7RxSwift5EventOyxGIegn_ADytIegnr_1EQyd__RszAA12ObserverTypeRd__r__lTR + 12
	30  RxSwift                             0x0000000107423156 $s7RxSwift5EventOyxGIegn_ADytIegnr_1EQyd__RszAA12ObserverTypeRd__r__lTRTA.40 + 54
	31  RxSwift                             0x000000010730c5bc $s7RxSwift5EventOyxGytIegnr_ADIegn_lTR + 12
	32  RxSwift                             0x000000010730ec20 $s7RxSwift5EventOyxGytIegnr_ADIegn_lTRTA.8 + 32
	33  RxSwift                             0x000000010730e34e $s7RxSwift8dispatchyyAA3BagVyyAA5EventOyxGcG_AGtlF + 606
	34  RxSwift                             0x000000010741d7aa $s7RxSwift36ShareReplay1WhileConnectedConnection33_E9FE621655D67A613BF2FC2D9B3041FCLLC2onyyAA5EventOyxGF + 138
	35  RxSwift                             0x000000010741f1a0 $s7RxSwift36ShareReplay1WhileConnectedConnection33_E9FE621655D67A613BF2FC2D9B3041FCLLCyxGAA12ObserverTypeA2aFP2onyyAA5EventOy1EQzGFTW + 16
	36  RxSwift                             0x000000010742bdb3 $s7RxSwift4SinkC9forwardOnyyAA5EventOy1EQzGF + 275
	37  RxSwift                             0x000000010743cc20 $s7RxSwift14SwitchSinkIter33_329C7BE5E760F8B243CD9FB0AF8C1442LLC16_synchronized_onyyAA5EventOy1EQy_GF + 864
	38  RxSwift                             0x000000010743cf49 $s7RxSwift14SwitchSinkIter33_329C7BE5E760F8B243CD9FB0AF8C1442LLCyxq_q0_GAA18SynchronizedOnTypeA2aFP16_synchronized_onyyAA5EventOy1EQzGFTW + 9
	39  RxSwift                             0x000000010744278f $s7RxSwift18SynchronizedOnTypePAAE012synchronizedD0yyAA5EventOy1EQzGF + 175
	40  RxSwift                             0x000000010743c8aa $s7RxSwift14SwitchSinkIter33_329C7BE5E760F8B243CD9FB0AF8C1442LLC2onyyAA5EventOy1EQy_GF + 282
	41  RxSwift                             0x000000010743cf20 $s7RxSwift14SwitchSinkIter33_329C7BE5E760F8B243CD9FB0AF8C1442LLCyxq_q0_GAA12ObserverTypeA2aFP2onyyAA5EventOy1EQzGFTW + 16
	42  RxSwift                             0x0000000107303ac3 $sTA + 83
	43  RxSwift                             0x000000010730bfcc $s7RxSwift5EventOyxGIegn_ADytIegnr_1EQyd__RszAA12ObserverTypeRd__r__lTR + 12
	44  RxSwift                             0x00000001073ec9d6 $s7RxSwift5EventOyxGIegn_ADytIegnr_1EQyd__RszAA12ObserverTypeRd__r__lTRTA + 54
	45  RxSwift                             0x000000010730c5bc $s7RxSwift5EventOyxGytIegnr_ADIegn_lTR + 12
	46  RxSwift                             0x000000010730ec20 $s7RxSwift5EventOyxGytIegnr_ADIegn_lTRTA.8 + 32
	47  RxSwift                             0x000000010730e34e $s7RxSwift8dispatchyyAA3BagVyyAA5EventOyxGcG_AGtlF + 606
	48  RxSwift                             0x00000001073eb5d2 $s7RxSwift14PublishSubjectC2onyyAA5EventOyxGF + 130
	49  RxSwift                             0x00000001073ed290 $s7RxSwift14PublishSubjectCyxGAA12ObserverTypeA2aEP2onyyAA5EventOy1EQzGFTW + 16
	50  RxSwift                             0x000000010742bdb3 $s7RxSwift4SinkC9forwardOnyyAA5EventOy1EQzGF + 275
	51  RxSwift                             0x000000010739b7eb $s7RxSwift10FilterSink33_172A575932639FDD42969ED91F7BE949LLC2onyyAA5EventOy1EQzGF + 715
	52  RxSwift                             0x000000010739c4e0 $s7RxSwift10FilterSink33_172A575932639FDD42969ED91F7BE949LLCyxGAA12ObserverTypeA2aFP2onyyAA5EventOy1EQzGFTW + 16
	53  RxSwift                             0x000000010742bdb3 $s7RxSwift4SinkC9forwardOnyyAA5EventOy1EQzGF + 275
	54  RxSwift                             0x000000010746ef50 $s7RxSwift18WithLatestFromSink33_CF69D82A190E869E15F230EB33D8E9CBLLC16_synchronized_onyyAA5EventOyxGF + 1264
	55  RxSwift                             0x000000010746ffb9 $s7RxSwift18WithLatestFromSink33_CF69D82A190E869E15F230EB33D8E9CBLLCyxq_q0_GAA18SynchronizedOnTypeA2aFP16_synchronized_onyyAA5EventOy1EQzGFTW + 9
	56  RxSwift                             0x000000010744278f $s7RxSwift18SynchronizedOnTypePAAE012synchronizedD0yyAA5EventOy1EQzGF + 175
	57  RxSwift                             0x000000010746ea56 $s7RxSwift18WithLatestFromSink33_CF69D82A190E869E15F230EB33D8E9CBLLC2onyyAA5EventOyxGF + 166
	58  RxSwift                             0x000000010746ff90 $s7RxSwift18WithLatestFromSink33_CF69D82A190E869E15F230EB33D8E9CBLLCyxq_q0_GAA12ObserverTypeA2aFP2onyyAA5EventOy1EQzGFTW + 16
	59  RxSwift                             0x000000010742bdb3 $s7RxSwift4SinkC9forwardOnyyAA5EventOy1EQzGF + 275
	60  RxSwift                             0x00000001074378d8 $s7RxSwift15SubscribeOnSink33_B44C3DD7F62EF81799E6347E59A266A2LLC2onyyAA5EventOy1EQzGF + 280
	61  RxSwift                             0x0000000107438a90 $s7RxSwift15SubscribeOnSink33_B44C3DD7F62EF81799E6347E59A266A2LLCyxq_GAA12ObserverTypeA2aFP2onyyAA5EventOy1EQzGFTW + 16
	62  RxSwift                             0x0000000107303ac3 $sTA + 83
	63  RxSwift                             0x000000010730bfcc $s7RxSwift5EventOyxGIegn_ADytIegnr_1EQyd__RszAA12ObserverTypeRd__r__lTR + 12
	64  RxSwift                             0x0000000107423066 $s7RxSwift5EventOyxGIegn_ADytIegnr_1EQyd__RszAA12ObserverTypeRd__r__lTRTA + 54
	65  RxSwift                             0x000000010730c5bc $s7RxSwift5EventOyxGytIegnr_ADIegn_lTR + 12
	66  RxSwift                             0x000000010730ec20 $s7RxSwift5EventOyxGytIegnr_ADIegn_lTRTA.8 + 32
	67  RxSwift                             0x000000010730e34e $s7RxSwift8dispatchyyAA3BagVyyAA5EventOyxGcG_AGtlF + 606
	68  RxSwift                             0x00000001074206da $s7RxSwift29ShareWhileConnectedConnection33_E9FE621655D67A613BF2FC2D9B3041FCLLC2onyyAA5EventOyxGF + 138
	69  RxSwift                             0x0000000107421c80 $s7RxSwift29ShareWhileConnectedConnection33_E9FE621655D67A613BF2FC2D9B3041FCLLCyxGAA12ObserverTypeA2aFP2onyyAA5EventOy1EQzGFTW + 16
	70  RxSwift                             0x000000010742bdb3 $s7RxSwift4SinkC9forwardOnyyAA5EventOy1EQzGF + 275
	71  RxSwift                             0x000000010744e1c3 $s7RxSwift13TakeUntilSink33_991BF34058B438BC3F322FA2B2904AFELLC16_synchronized_onyyAA5EventOy1EQy_GF + 387
	72  RxSwift                             0x000000010744f1a9 $s7RxSwift13TakeUntilSink33_991BF34058B438BC3F322FA2B2904AFELLCyxq_GAA18SynchronizedOnTypeA2aFP16_synchronized_onyyAA5EventOy1EQzGFTW + 9
	73  RxSwift                             0x000000010744278f $s7RxSwift18SynchronizedOnTypePAAE012synchronizedD0yyAA5EventOy1EQzGF + 175
	74  RxSwift                             0x000000010744e032 $s7RxSwift13TakeUntilSink33_991BF34058B438BC3F322FA2B2904AFELLC2onyyAA5EventOy1EQy_GF + 242
	75  RxSwift                             0x000000010744f190 $s7RxSwift13TakeUntilSink33_991BF34058B438BC3F322FA2B2904AFELLCyxq_GAA12ObserverTypeA2aFP2onyyAA5EventOy1EQzGFTW + 16
	76  RxSwift                             0x000000010742bdb3 $s7RxSwift4SinkC9forwardOnyyAA5EventOy1EQzGF + 275
	77  RxSwift                             0x000000010736efe3 $s7RxSwift23AnonymousObservableSink33_95EBF5692819D58425EC2DD0512D115ALLC2onyyAA5EventOy1EQzGF + 419
	78  RxSwift                             0x000000010736f3b0 $s7RxSwift23AnonymousObservableSink33_95EBF5692819D58425EC2DD0512D115ALLCyxGAA12ObserverTypeA2aFP2onyyAA5EventOy1EQzGFTW + 16
	79  RxSwift                             0x0000000107303ac3 $sTA + 83
	80  RxSwift                             0x000000010730305f $s7RxSwift11AnyObserverV2onyyAA5EventOyxGF + 79
	81  RxCocoa                             0x000000010712a780 $s7RxSwift8ReactiveV0A5CocoaSo15UIBarButtonItemCRbzlE3tapAD12ControlEventVyytGvgAA10ObservableCyytGyXEfU_AA10Disposable_pAA11AnyObserverVyytGcfU_yycfU_ + 80
	82  RxCocoa                             0x000000010712bf71 $s7RxSwift8ReactiveV0A5CocoaSo15UIBarButtonItemCRbzlE3tapAD12ControlEventVyytGvgAA10ObservableCyytGyXEfU_AA10Disposable_pAA11AnyObserverVyytGcfU_yycfU_TA + 17
	83  RxCocoa                             0x000000010712b3b1 $s7RxCocoa19BarButtonItemTargetC6actionyyyXlF + 353
	84  RxCocoa                             0x000000010712b40c $s7RxCocoa19BarButtonItemTargetC6actionyyyXlFTo + 60
	85  UIKitCore                           0x0000000111f81204 -[UIApplication sendAction:to:from:forEvent:] + 83
	86  UIKitCore                           0x00000001116eb963 __45-[_UIButtonBarTargetAction _invoke:forEvent:]_block_invoke + 154
	87  UIKitCore                           0x00000001116eb89c -[_UIButtonBarTargetAction _invoke:forEvent:] + 152
	88  UIKitCore                           0x0000000111f81204 -[UIApplication sendAction:to:from:forEvent:] + 83
	89  UIKitCore                           0x00000001119d6c19 -[UIControl sendAction:to:forEvent:] + 67
	90  UIKitCore                           0x00000001119d6f36 -[UIControl _sendActionsForEvents:withEvent:] + 450
	91  UIKitCore                           0x00000001119d5eec -[UIControl touchesEnded:withEvent:] + 583
	92  UIKitCore                           0x0000000111fb9eee -[UIWindow _sendTouchesForEvent:] + 2547
	93  UIKitCore                           0x0000000111fbb5d2 -[UIWindow sendEvent:] + 4079
	94  UIKitCore                           0x0000000111f99d16 -[UIApplication sendEvent:] + 356
	95  UIKitCore                           0x000000011206a293 __dispatchPreprocessedEventFromEventQueue + 3232
	96  UIKitCore                           0x000000011206cbb9 __handleEventQueueInternal + 5911
	97  CoreFoundation                      0x000000010885cbe1 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	98  CoreFoundation                      0x000000010885c463 __CFRunLoopDoSources0 + 243
	99  CoreFoundation                      0x0000000108856b1f __CFRunLoopRun + 1231
	100 CoreFoundation                      0x0000000108856302 CFRunLoopRunSpecific + 626
	101 GraphicsServices                    0x000000010f56a2fe GSEventRunModal + 65
	102 UIKitCore                           0x0000000111f7fba2 UIApplicationMain + 140
	103 RxMultipeerGroupChat                0x0000000106ce165b main + 75
	104 libdyld.dylib                       0x000000010bb8e541 start + 1
	105 ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) `

**Comment by danielt1263** [comment]
What was the Room Name and Display Name that you used?

**Comment by adriansergheev** [comment]
123
123

**Comment by danielt1263** [comment]
I found and fixed the issue in commit: eb79db1098b0fc5bfd2b1e4c48e0546592c34e7f. Thanks @andriansergheev!
